spring:
  config:
    activate:
      on-profile: dev

application:
  mapbox:
    enabled: ${APPLICATION_MAPBOX_ENABLED:false}
    api-base-url: ${APPLICATION_MAPBOX_API_BASE_URL:https://api.mapbox.com}
    access-token: ${APPLICATION_MAPBOX_ACCESS_TOKEN:}
    style-url: ${APPLICATION_MAPBOX_STYLE_URL:mapbox://styles/mapbox/streets-v12}
    geocoding-limit: ${APPLICATION_MAPBOX_GEOCODING_LIMIT:5}

