# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: liferadar
services:
  app:
    image: liferadar
    environment:
      - _JAVA_OPTIONS=-Xmx1024m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://liferadardb.c54u8c6u8l8z.eu-central-1.rds.amazonaws.com:5432/liferadar
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://liferadardb.c54u8c6u8l8z.eu-central-1.rds.amazonaws.com:5432/liferadar
    ports:
      - 127.0.0.1:80:80
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:80/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      postgresql:
        condition: service_healthy
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
